You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Access denied for user 'ai2'@'172.24.0.2' (using password: YES)
    at Object.createConnection (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/promise.js:253:31)
    at _0x212e8f (/src/dist/modules/database/initDatabase.js:1:6897)
    at _0x30ba24 (/src/dist/main.js:1:5383)
    at Object.<anonymous> (/src/dist/main.js:1:15205)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:304:25
    at wrapper (/usr/local/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
    at next (/usr/local/lib/node_modules/pm2/node_modules/async/waterfall.js:96:20)
    at /usr/local/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Utility.js:186:13)
    at WriteStream.emit (node:events:517:28)
    at node:internal/fs/streams:77:16
    at FSReqCallback.oncomplete (node:fs:192:23)
2024-03-12 00:30:24: [31m[Nest] 30  - [39m03/12/2024, 12:30:24 AM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (1)...[39m
2024-03-12 00:30:24: Error: Access denied for user 'ai2'@'172.24.0.2' (using password: YES)
    at Packet.asError (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/packets/packet.js:728:17)
    at ClientHandshake.execute (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2024-03-12 00:30:24: [31m[Nest] 30  - [39m03/12/2024, 12:30:24 AM [31m  ERROR[39m [38;5;3m[MailerService] [39m[31mError occurred while verifying the transporter}: Invalid login: 550 User has no permission[39m
2024-03-12 00:30:27: [31m[Nest] 30  - [39m03/12/2024, 12:30:27 AM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (2)...[39m
2024-03-12 00:30:27: Error: Access denied for user 'ai2'@'172.24.0.2' (using password: YES)
    at Packet.asError (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/packets/packet.js:728:17)
    at ClientHandshake.execute (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2024-03-12 00:30:30: [31m[Nest] 30  - [39m03/12/2024, 12:30:30 AM [31m  ERROR[39m [38;5;3m[TypeOrmModule] [39m[31mUnable to connect to the database. Retrying (3)...[39m
2024-03-12 00:30:30: Error: Access denied for user 'ai2'@'172.24.0.2' (using password: YES)
    at Packet.asError (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/packets/packet.js:728:17)
    at ClientHandshake.execute (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/commands/command.js:29:26)
    at PoolConnection.handlePacket (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/src/node_modules/.pnpm/mysql2@3.9.2/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
